<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.0</Version>
    <Deterministic>true</Deterministic>
    <Authors>沙漠尽头的狼</Authors>
    <Copyright>https://codewf.com</Copyright>
    <RepositoryUrl>https://github.com/dotnet9/HomeLedger</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
