<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Semi.Avalonia" />
    <PackageReference Include="Prism.Avalonia" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HomeLedger.Core\HomeLedger.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="..\..\logo.png" Link="Assets\logo.png" />
    <AvaloniaResource Include="..\..\logo.ico" Link="Assets\logo.ico" />
  </ItemGroup>
</Project>
